enum enum_relationship_type {
  mother
  father
  guardian
}

enum enum_rubric_level {
  exemplary
  accomplished
  developing
  beginning
}

enum enum_sch_space_type {
  classroom
  laboratory
  gymnasium
  pool
  library
  auditorium
}

enum enum_sub_thread_res_type {
  comment
  answer
}

enum enum_sub_thread_type {
  discussion
  question
  announcement
  qanda
}

enum enum_task_block_type {
  heading
  rich_text
  math_input
  image
  video
  audio
  fill_blank
  choice
  whiteboard
  matching
  short_answer
}

enum enum_task_status {
  draft
  in_progress
  published
  completed
  locked
  graded
}

enum enum_task_type {
  lesson
  assessment
  homework
}

enum enum_tt_queue_status {
  queued
  in_progress
  completed
  failed
}

enum enum_gender {
  male
  female
  "non-binary"
  other
  unspecified
}

enum enum_user_honorific {
  Mr
  Ms
  Mrs
  Dr
  Prof
}

enum enum_user_type {
  N
  student
  teacher
  guardian
  principal
  schoolAdmin
  systemAdmin
}

enum enum_whiteboard_object_type {
  Rect
  Circle
  Path
  Textbox
  Image
}

enum enum_year_level {
  N
  F
  "1"
  "2"
  "3"
  "4"
  "5"
  "6"
  "7"
  "8"
  "9"
  "10"
  "10A"
  "11"
  "12"
  "13"
}

table cm_ass_pln_la_std {
  id integer [pk, not null]
  cm_itm_ass_pln_id integer [not null]
  la_std_id integer [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table cm_ass_pln_res {
  id integer [pk, not null]
  cm_itm_ass_pln_id integer [not null]
  res_id integer [not null]
}

table cmps {
  id integer [pk, not null]
  sch_id integer [not null]
  name text [not null]
  address text [not null]
  description text
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table cmps_evt {
  id integer [pk, not null]
  cmps_id integer [not null]
  name text [not null]
  start_ts timestamp [not null]
  end_ts timestamp [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table cb_chat {
  id integer [pk, not null]
  user_id uuid
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table cb_msg {
  id integer [pk, not null]
  author_id uuid
  cb_chat_id integer [not null]
  content text [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table cls_task_block_res {
  id integer [pk, not null]
  task_block_id integer [not null]
  author_id uuid [not null]
  class_task_id integer [not null]
  response jsonb
  feedback text
  marks "double precision"
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table cls_task_res {
  id integer [pk, not null]
  cls_task_id integer [not null]
  comment text
  feedback text
  author_id uuid [not null]
  teacher_id uuid
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table task_response_resource {
  id integer [pk, not null]
  cls_task_res_id integer [not null]
  res_id integer [not null]
  author_id uuid [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table sub_core {
  id integer [pk, not null]
  name text [not null]
  description text
  cur_sub_id integer [not null]
  sch_id integer [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table cm_itm {
  id integer [pk, not null]
  sub_off_id integer [not null]
  topic text [not null]
  description text
  start_week integer
  duration integer
  semester integer
  color text [default: '#3B82F6']
  image_base64 text
  original_id integer
  version integer [not null, default: 1]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    
    (original_id, version) [name: 'cm_itm_original_id_version_unique', unique]
  }
}

table cm_itm_ass_pln {
  id integer [pk, not null]
  cm_itm_id integer [not null]
  name text [not null]
  scope text[]
  description text
  rubric_id integer
  image_base64 text
  original_id integer
  version integer [not null, default: 1]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    
    (original_id, version) [name: 'cm_itm_ass_pln_original_id_version_unique', unique]
  }
}

table cm_itm_la {
  id integer [pk, not null]
  cm_itm_id integer [not null]
  lrn_a_id integer [not null]
  original_id integer
  version integer [not null, default: 1]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    
    (original_id, version) [name: 'cm_itm_la_original_id_version_unique', unique]
  }
}

table cm_itm_les_pln {
  id integer [pk, not null]
  cm_itm_id integer [not null]
  name text [not null]
  scope text[]
  description text
  image_base64 text
  original_id integer
  version integer [not null, default: 1]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    
    (original_id, version) [name: 'cm_itm_les_pln_original_id_version_unique', unique]
  }
}

table cm_itm_res {
  id integer [pk, not null]
  cm_itm_id integer [not null]
  resource_id integer [not null]
  original_id integer
  version integer [not null, default: 1]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    
    (original_id, version) [name: 'cm_itm_res_original_id_version_unique', unique]
  }
}

table crclm {
  id integer [pk, not null]
  name text [not null]
  version text [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table crclm_sub {
  id integer [pk, not null]
  name text [not null]
  cur_id integer [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table sub_elec {
  id integer [pk, not null]
  name text [not null]
  description text
  sch_id integer [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table fet_activity {
  id integer [pk, not null]
  tt_id integer [not null]
  teacher_id text [not null]
  subject_id integer [not null]
  tt_group_id integer [not null]
  space_id integer [not null]
  tt_day_id integer [not null]
  tt_period_id integer [not null]
  duration integer [not null]
}

table crclm_sub_la {
  id integer [pk, not null]
  cur_sub_id integer [not null]
  name text [not null]
  description text
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table lrn_a_std {
  id integer [pk, not null]
  lrn_a_id integer [not null]
  name text [not null]
  description text
  yearLevel enum_year_level [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table cm_les_pln_la_std {
  id integer [pk, not null]
  cm_itm_les_pln_id integer [not null]
  la_std_id integer [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table cm_les_pln_res {
  id integer [pk, not null]
  cm_itm_les_pln_id integer [not null]
  res_id integer [not null]
}

table res {
  id integer [pk, not null]
  file_name text [not null]
  object_key text [not null]
  bucket_name text [not null, default: 'schools']
  content_type text [not null]
  file_size integer [not null]
  resource_type text [not null]
  uploaded_by uuid [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table rubric {
  id integer [pk, not null]
  title text [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table rubric_cell {
  id integer [pk, not null]
  row_id integer [not null]
  level enum_rubric_level [not null]
  description text [not null]
  marks "double precision" [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table rubric_feedback {
  id integer [pk, not null]
  class_task_response_id integer [not null]
  rubric_row_id integer [not null]
  rubric_cell_id integer [not null]
  feedback text
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table rubric_row {
  id integer [pk, not null]
  rubric_id integer [not null]
  title text [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table sch {
  id integer [pk, not null]
  name text [not null, unique]
  logo_url text
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table sch_bldng {
  id integer [pk, not null]
  cmps_id integer [not null]
  name text [not null]
  description text
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    (cmps_id, name) [name: 'sch_bldng_cmps_id_name_unique', unique]
  }
}

table sch_evt {
  id integer [pk, not null]
  sch_id integer [not null]
  name text [not null]
  start_ts timestamp [not null]
  end_ts timestamp [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table sch_space {
  id integer [pk, not null]
  sch_bldng_id integer [not null]
  name text [not null]
  type enum_sch_space_type [not null]
  capacity integer
  description text
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    (sch_bldng_id, name) [name: 'sch_space_sch_bldng_id_name_unique', unique]
  }
}

table session {
  id text [pk, not null]
  secret_hash text [not null]
  user_id uuid [not null]
  lastVerifiedAt timestamp [not null]
  createdAt timestamp [not null]
}

table lrn_a_std_elab {
  id integer [pk, not null]
  lrn_a_std_id integer [not null]
  name text [not null]
  std_elab text [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table sub {
  id integer [pk, not null]
  name text [not null]
  sch_id integer [not null]
  sub_core_id integer
  sub_elec_id integer
  yearLevel enum_year_level [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    (sch_id, name) [name: 'sub_sch_id_name_unique', unique]
    
  }
}

table sub_off_cls_allo {
  id integer [pk, not null]
  sub_off_cls_id integer [not null]
  sch_spa_id integer [not null]
  start_ts timestamp [not null]
  end_ts timestamp [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table sub_off_cls_allo_att {
  id integer [pk, not null]
  sub_class_allo_id integer [not null]
  user_id uuid [not null]
  was_absent boolean [not null, default: false]
  did_attend boolean [not null, default: false]
  attendance_note text
  behaviour_note text
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    (sub_class_allo_id, user_id) [name: 'sub_off_cls_allo_att_sub_class_allo_id_user_id_unique', unique]
  }
}

table sub_off {
  id integer [pk, not null]
  sub_id integer [not null]
  year integer [not null]
  semester integer [not null]
  campus_id integer [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table sub_off_cls {
  id integer [pk, not null]
  name text [not null]
  sub_off_id integer [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    (sub_off_id, name) [name: 'sub_off_cls_sub_off_id_name_unique', unique]
  }
}

table sub_off_cls_evt {
  id integer [pk, not null]
  sub_off_cls_id integer [not null]
  name text [not null]
  start_ts timestamp [not null]
  end_ts timestamp [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table sub_off_cls_res {
  id integer [pk, not null]
  title text
  description text
  sub_off_cls_id integer [not null]
  res_id integer [not null]
  cm_item_id integer
  author_id uuid [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table sub_off_class_task {
  id integer [pk, not null]
  index integer [not null]
  status enum_task_status [not null, default: 'draft']
  sub_off_class_id integer [not null]
  task_id integer [not null]
  author_id uuid [not null]
  cm_item_id integer
  week integer
  dueDate timestamp
  is_archived boolean [not null, default: false]
  rubric_id integer
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table sub_off_evt {
  id integer [pk, not null]
  sub_off_id integer [not null]
  name text [not null]
  start_ts timestamp [not null]
  end_ts timestamp [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table sub_thread {
  id integer [pk, not null]
  type enum_sub_thread_type [not null]
  sub_off_id integer [not null]
  user_id uuid [not null]
  title text [not null]
  content text [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table sub_thread_resp {
  id integer [pk, not null]
  type enum_sub_thread_res_type [not null]
  sub_thread_id integer [not null]
  user_id uuid [not null]
  content text [not null]
  parent_id integer
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table task {
  id integer [pk, not null]
  title text [not null]
  type enum_task_type [not null]
  description text [not null]
  rubric_id integer
  original_id integer
  version integer [not null, default: 1]
  subject_offering_id integer [not null]
  ai_tutor_enabled boolean [not null, default: true]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    
    (original_id, version) [name: 'task_original_id_version_unique', unique]
  }
}

table task_block {
  id integer [pk, not null]
  task_id integer [not null]
  type enum_task_block_type [not null]
  config jsonb [not null]
  index integer [not null, default: 0]
  available_marks integer
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table task_std {
  id integer [pk, not null]
  task_id integer [not null]
  lrn_a_std_id integer [not null]
}

table tt {
  id integer [pk, not null]
  sch_id integer [not null]
  sch_year integer [not null]
  name text [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    (sch_id, name) [name: 'tt_sch_id_name_unique', unique]
  }
}

table tt_activity {
  id integer [pk, not null]
  tt_id integer [not null]
  subject_id integer [not null]
  teacher_id uuid [not null]
  tt_group_id integer [not null]
  periods_per_instance integer [not null, default: 1]
  total_periods integer [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table tt_day {
  id integer [pk, not null]
  tt_id integer [not null]
  day integer [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table tt_group {
  id integer [pk, not null]
  tt_id integer [not null]
  yearLevel enum_year_level [not null]
  name text [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table tt_group_member {
  id integer [pk, not null]
  tt_group_id integer [not null]
  user_id uuid [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    (tt_group_id, user_id) [name: 'tt_group_member_tt_group_id_user_id_unique', unique]
  }
}

table tt_period {
  id integer [pk, not null]
  tt_id integer [not null]
  start_time time [not null]
  end_time time [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table tt_queue {
  id integer [pk, not null]
  tt_id integer [not null]
  user_id uuid [not null]
  file_name text [not null]
  status enum_tt_queue_status [not null, default: 'queued']
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table user {
  id uuid [pk, not null, default: `gen_random_uuid()`]
  email text [not null, unique]
  password_hash text
  google_id text [unique]
  microsoft_id text [unique]
  school_id integer [not null]
  type enum_user_type [not null, default: 'N']
  gender enum_gender [not null, default: 'unspecified']
  date_of_birth "timestamp with time zone"
  honorific enum_user_honorific
  yearLevel enum_year_level [not null]
  first_name text [not null]
  middle_name text
  last_name text [not null]
  avatar_url text
  verification_code text
  email_verified boolean [not null, default: false]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table user_cmps {
  id integer [pk, not null]
  user_id uuid [not null]
  cmps_id integer [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table user_relationship {
  id uuid [pk, not null, default: `gen_random_uuid()`]
  user_id uuid [not null]
  related_user_id uuid [not null]
  relationshipType enum_relationship_type [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table user_sub_off {
  id integer [pk, not null]
  user_id uuid [not null]
  sub_off_id integer [not null]
  is_complete integer [not null, default: 0]
  is_archived integer [not null, default: 0]
  color integer [not null, default: 100]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table sub_off_cls_user {
  id integer [pk, not null]
  user_id uuid [not null]
  sub_off_class_id integer [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    (user_id, sub_off_class_id) [name: 'sub_off_cls_user_user_id_sub_off_class_id_unique', unique]
  }
}

table whiteboard {
  id integer [pk, not null]
  task_id integer [not null]
  title text
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table whiteboard_object {
  id integer [pk, not null]
  whiteboard_id integer [not null]
  object_id text [not null, unique]
  objectType enum_whiteboard_object_type [not null]
  object_data jsonb [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

ref cm_ass_pln_la_std_cm_itm_ass_pln_id_cm_itm_ass_pln_id_fk: cm_ass_pln_la_std.cm_itm_ass_pln_id > cm_itm_ass_pln.id [delete: cascade, update: no action]

ref cm_ass_pln_la_std_la_std_id_lrn_a_std_id_fk: cm_ass_pln_la_std.la_std_id > lrn_a_std.id [delete: cascade, update: no action]

ref cm_ass_pln_res_cm_itm_ass_pln_id_cm_itm_ass_pln_id_fk: cm_ass_pln_res.cm_itm_ass_pln_id > cm_itm_ass_pln.id [delete: cascade, update: no action]

ref cm_ass_pln_res_res_id_res_id_fk: cm_ass_pln_res.res_id > res.id [delete: cascade, update: no action]

ref cmps_sch_id_sch_id_fk: cmps.sch_id > sch.id [delete: cascade, update: no action]

ref cmps_evt_cmps_id_cmps_id_fk: cmps_evt.cmps_id > cmps.id [delete: cascade, update: no action]

ref cb_chat_user_id_user_id_fk: cb_chat.user_id > user.id [delete: cascade, update: no action]

ref cb_msg_author_id_user_id_fk: cb_msg.author_id > user.id [delete: cascade, update: no action]

ref cb_msg_cb_chat_id_cb_chat_id_fk: cb_msg.cb_chat_id > cb_chat.id [delete: cascade, update: no action]

ref cls_task_block_res_task_block_id_task_block_id_fk: cls_task_block_res.task_block_id > task_block.id [delete: cascade, update: no action]

ref cls_task_block_res_author_id_user_id_fk: cls_task_block_res.author_id > user.id [delete: cascade, update: no action]

ref cls_task_block_res_class_task_id_sub_off_class_task_id_fk: cls_task_block_res.class_task_id > sub_off_class_task.id [delete: cascade, update: no action]

ref cls_task_res_cls_task_id_sub_off_class_task_id_fk: cls_task_res.cls_task_id > sub_off_class_task.id [delete: cascade, update: no action]

ref cls_task_res_author_id_user_id_fk: cls_task_res.author_id > user.id [delete: cascade, update: no action]

ref cls_task_res_teacher_id_user_id_fk: cls_task_res.teacher_id > user.id [delete: cascade, update: no action]

ref task_response_resource_cls_task_res_id_cls_task_res_id_fk: task_response_resource.cls_task_res_id > cls_task_res.id [delete: cascade, update: no action]

ref task_response_resource_res_id_res_id_fk: task_response_resource.res_id > res.id [delete: cascade, update: no action]

ref task_response_resource_author_id_user_id_fk: task_response_resource.author_id > user.id [delete: cascade, update: no action]

ref sub_core_cur_sub_id_crclm_sub_id_fk: sub_core.cur_sub_id > crclm_sub.id [delete: cascade, update: no action]

ref sub_core_sch_id_sch_id_fk: sub_core.sch_id > sch.id [delete: cascade, update: no action]

ref cm_itm_sub_off_id_sub_off_id_fk: cm_itm.sub_off_id > sub_off.id [delete: cascade, update: no action]

ref cm_itm_original_id_cm_itm_id_fk: cm_itm.original_id > cm_itm.id [delete: cascade, update: no action]

ref cm_itm_ass_pln_cm_itm_id_cm_itm_id_fk: cm_itm_ass_pln.cm_itm_id > cm_itm.id [delete: cascade, update: no action]

ref cm_itm_ass_pln_rubric_id_rubric_id_fk: cm_itm_ass_pln.rubric_id > rubric.id [delete: set null, update: no action]

ref cm_itm_ass_pln_original_id_cm_itm_ass_pln_id_fk: cm_itm_ass_pln.original_id > cm_itm_ass_pln.id [delete: cascade, update: no action]

ref cm_itm_la_cm_itm_id_cm_itm_id_fk: cm_itm_la.cm_itm_id > cm_itm.id [delete: cascade, update: no action]

ref cm_itm_la_lrn_a_id_crclm_sub_la_id_fk: cm_itm_la.lrn_a_id > crclm_sub_la.id [delete: cascade, update: no action]

ref cm_itm_la_original_id_cm_itm_la_id_fk: cm_itm_la.original_id > cm_itm_la.id [delete: cascade, update: no action]

ref cm_itm_les_pln_cm_itm_id_cm_itm_id_fk: cm_itm_les_pln.cm_itm_id > cm_itm.id [delete: cascade, update: no action]

ref cm_itm_les_pln_original_id_cm_itm_les_pln_id_fk: cm_itm_les_pln.original_id > cm_itm_les_pln.id [delete: cascade, update: no action]

ref cm_itm_res_cm_itm_id_cm_itm_id_fk: cm_itm_res.cm_itm_id > cm_itm.id [delete: cascade, update: no action]

ref cm_itm_res_resource_id_res_id_fk: cm_itm_res.resource_id > res.id [delete: cascade, update: no action]

ref cm_itm_res_original_id_cm_itm_res_id_fk: cm_itm_res.original_id > cm_itm_res.id [delete: cascade, update: no action]

ref crclm_sub_cur_id_crclm_id_fk: crclm_sub.cur_id > crclm.id [delete: cascade, update: no action]

ref sub_elec_sch_id_sch_id_fk: sub_elec.sch_id > sch.id [delete: cascade, update: no action]

ref fet_activity_tt_id_tt_id_fk: fet_activity.tt_id > tt.id [delete: cascade, update: no action]

ref crclm_sub_la_cur_sub_id_crclm_sub_id_fk: crclm_sub_la.cur_sub_id > crclm_sub.id [delete: cascade, update: no action]

ref lrn_a_std_lrn_a_id_crclm_sub_la_id_fk: lrn_a_std.lrn_a_id > crclm_sub_la.id [delete: cascade, update: no action]

ref cm_les_pln_la_std_cm_itm_les_pln_id_cm_itm_les_pln_id_fk: cm_les_pln_la_std.cm_itm_les_pln_id > cm_itm_les_pln.id [delete: cascade, update: no action]

ref cm_les_pln_la_std_la_std_id_lrn_a_std_id_fk: cm_les_pln_la_std.la_std_id > lrn_a_std.id [delete: cascade, update: no action]

ref cm_les_pln_res_cm_itm_les_pln_id_cm_itm_les_pln_id_fk: cm_les_pln_res.cm_itm_les_pln_id > cm_itm_les_pln.id [delete: cascade, update: no action]

ref cm_les_pln_res_res_id_res_id_fk: cm_les_pln_res.res_id > res.id [delete: cascade, update: no action]

ref res_uploaded_by_user_id_fk: res.uploaded_by > user.id [delete: cascade, update: no action]

ref rubric_cell_row_id_rubric_row_id_fk: rubric_cell.row_id > rubric_row.id [delete: cascade, update: no action]

ref rubric_feedback_class_task_response_id_cls_task_res_id_fk: rubric_feedback.class_task_response_id > cls_task_res.id [delete: cascade, update: no action]

ref rubric_feedback_rubric_row_id_rubric_row_id_fk: rubric_feedback.rubric_row_id > rubric_row.id [delete: cascade, update: no action]

ref rubric_feedback_rubric_cell_id_rubric_cell_id_fk: rubric_feedback.rubric_cell_id > rubric_cell.id [delete: cascade, update: no action]

ref rubric_row_rubric_id_rubric_id_fk: rubric_row.rubric_id > rubric.id [delete: cascade, update: no action]

ref sch_bldng_cmps_id_cmps_id_fk: sch_bldng.cmps_id > cmps.id [delete: cascade, update: no action]

ref sch_evt_sch_id_sch_id_fk: sch_evt.sch_id > sch.id [delete: cascade, update: no action]

ref sch_space_sch_bldng_id_sch_bldng_id_fk: sch_space.sch_bldng_id > sch_bldng.id [delete: cascade, update: no action]

ref session_user_id_user_id_fk: session.user_id > user.id [delete: no action, update: no action]

ref lrn_a_std_elab_lrn_a_std_id_lrn_a_std_id_fk: lrn_a_std_elab.lrn_a_std_id > lrn_a_std.id [delete: cascade, update: no action]

ref sub_sch_id_sch_id_fk: sub.sch_id > sch.id [delete: cascade, update: no action]

ref sub_sub_core_id_sub_core_id_fk: sub.sub_core_id > sub_core.id [delete: set null, update: no action]

ref sub_sub_elec_id_sub_elec_id_fk: sub.sub_elec_id > sub_elec.id [delete: set null, update: no action]

ref sub_off_cls_allo_sub_off_cls_id_sub_off_cls_id_fk: sub_off_cls_allo.sub_off_cls_id > sub_off_cls.id [delete: cascade, update: no action]

ref sub_off_cls_allo_sch_spa_id_sch_space_id_fk: sub_off_cls_allo.sch_spa_id > sch_space.id [delete: set null, update: no action]

ref sub_off_cls_allo_att_sub_class_allo_id_sub_off_cls_allo_id_fk: sub_off_cls_allo_att.sub_class_allo_id > sub_off_cls_allo.id [delete: cascade, update: no action]

ref sub_off_cls_allo_att_user_id_user_id_fk: sub_off_cls_allo_att.user_id > user.id [delete: cascade, update: no action]

ref sub_off_sub_id_sub_id_fk: sub_off.sub_id > sub.id [delete: cascade, update: no action]

ref sub_off_campus_id_cmps_id_fk: sub_off.campus_id > cmps.id [delete: cascade, update: no action]

ref sub_off_cls_sub_off_id_sub_off_id_fk: sub_off_cls.sub_off_id > sub_off.id [delete: cascade, update: no action]

ref sub_off_cls_evt_sub_off_cls_id_sub_off_cls_id_fk: sub_off_cls_evt.sub_off_cls_id > sub_off_cls.id [delete: cascade, update: no action]

ref sub_off_cls_res_sub_off_cls_id_sub_off_cls_id_fk: sub_off_cls_res.sub_off_cls_id > sub_off_cls.id [delete: cascade, update: no action]

ref sub_off_cls_res_res_id_res_id_fk: sub_off_cls_res.res_id > res.id [delete: cascade, update: no action]

ref sub_off_cls_res_cm_item_id_cm_itm_id_fk: sub_off_cls_res.cm_item_id > cm_itm.id [delete: cascade, update: no action]

ref sub_off_cls_res_author_id_user_id_fk: sub_off_cls_res.author_id > user.id [delete: cascade, update: no action]

ref sub_off_class_task_sub_off_class_id_sub_off_cls_id_fk: sub_off_class_task.sub_off_class_id > sub_off_cls.id [delete: cascade, update: no action]

ref sub_off_class_task_task_id_task_id_fk: sub_off_class_task.task_id > task.id [delete: cascade, update: no action]

ref sub_off_class_task_author_id_user_id_fk: sub_off_class_task.author_id > user.id [delete: cascade, update: no action]

ref sub_off_class_task_cm_item_id_cm_itm_id_fk: sub_off_class_task.cm_item_id > cm_itm.id [delete: cascade, update: no action]

ref sub_off_class_task_rubric_id_rubric_id_fk: sub_off_class_task.rubric_id > rubric.id [delete: set null, update: no action]

ref sub_off_evt_sub_off_id_sub_off_id_fk: sub_off_evt.sub_off_id > sub_off.id [delete: cascade, update: no action]

ref sub_thread_sub_off_id_sub_off_id_fk: sub_thread.sub_off_id > sub_off.id [delete: cascade, update: no action]

ref sub_thread_user_id_user_id_fk: sub_thread.user_id > user.id [delete: cascade, update: no action]

ref sub_thread_resp_sub_thread_id_sub_thread_id_fk: sub_thread_resp.sub_thread_id > sub_thread.id [delete: cascade, update: no action]

ref sub_thread_resp_user_id_user_id_fk: sub_thread_resp.user_id > user.id [delete: cascade, update: no action]

ref sub_thread_resp_parent_id_sub_thread_resp_id_fk: sub_thread_resp.parent_id > sub_thread_resp.id [delete: no action, update: no action]

ref sub_thread_resp_parent_id_sub_thread_resp_id_fk: sub_thread_resp.parent_id > sub_thread_resp.id [delete: cascade, update: no action]

ref task_rubric_id_rubric_id_fk: task.rubric_id > rubric.id [delete: set null, update: no action]

ref task_subject_offering_id_sub_off_id_fk: task.subject_offering_id > sub_off.id [delete: cascade, update: no action]

ref task_original_id_task_id_fk: task.original_id > task.id [delete: cascade, update: no action]

ref task_block_task_id_task_id_fk: task_block.task_id > task.id [delete: cascade, update: no action]

ref task_std_task_id_task_id_fk: task_std.task_id > task.id [delete: cascade, update: no action]

ref task_std_lrn_a_std_id_lrn_a_std_id_fk: task_std.lrn_a_std_id > lrn_a_std.id [delete: cascade, update: no action]

ref tt_sch_id_sch_id_fk: tt.sch_id > sch.id [delete: cascade, update: no action]

ref tt_activity_tt_id_tt_id_fk: tt_activity.tt_id > tt.id [delete: cascade, update: no action]

ref tt_activity_subject_id_sub_id_fk: tt_activity.subject_id > sub.id [delete: cascade, update: no action]

ref tt_activity_teacher_id_user_id_fk: tt_activity.teacher_id > user.id [delete: cascade, update: no action]

ref tt_activity_tt_group_id_tt_group_id_fk: tt_activity.tt_group_id > tt_group.id [delete: cascade, update: no action]

ref tt_day_tt_id_tt_id_fk: tt_day.tt_id > tt.id [delete: cascade, update: no action]

ref tt_group_tt_id_tt_id_fk: tt_group.tt_id > tt.id [delete: cascade, update: no action]

ref tt_group_member_tt_group_id_tt_group_id_fk: tt_group_member.tt_group_id > tt_group.id [delete: cascade, update: no action]

ref tt_group_member_user_id_user_id_fk: tt_group_member.user_id > user.id [delete: cascade, update: no action]

ref tt_period_tt_id_tt_id_fk: tt_period.tt_id > tt.id [delete: cascade, update: no action]

ref tt_queue_tt_id_tt_id_fk: tt_queue.tt_id > tt.id [delete: cascade, update: no action]

ref tt_queue_user_id_user_id_fk: tt_queue.user_id > user.id [delete: cascade, update: no action]

ref user_school_id_sch_id_fk: user.school_id > sch.id [delete: cascade, update: no action]

ref user_cmps_user_id_user_id_fk: user_cmps.user_id > user.id [delete: cascade, update: no action]

ref user_cmps_cmps_id_cmps_id_fk: user_cmps.cmps_id > cmps.id [delete: cascade, update: no action]

ref user_relationship_user_id_user_id_fk: user_relationship.user_id > user.id [delete: cascade, update: no action]

ref user_relationship_related_user_id_user_id_fk: user_relationship.related_user_id > user.id [delete: cascade, update: no action]

ref user_sub_off_user_id_user_id_fk: user_sub_off.user_id > user.id [delete: cascade, update: no action]

ref user_sub_off_sub_off_id_sub_off_id_fk: user_sub_off.sub_off_id > sub_off.id [delete: cascade, update: no action]

ref sub_off_cls_user_user_id_user_id_fk: sub_off_cls_user.user_id > user.id [delete: cascade, update: no action]

ref sub_off_cls_user_sub_off_class_id_sub_off_cls_id_fk: sub_off_cls_user.sub_off_class_id > sub_off_cls.id [delete: cascade, update: no action]

ref whiteboard_task_id_task_id_fk: whiteboard.task_id > task.id [delete: cascade, update: no action]

ref whiteboard_object_whiteboard_id_whiteboard_id_fk: whiteboard_object.whiteboard_id > whiteboard.id [delete: cascade, update: no action]