enum feedback_level {
  met
  no
  partial
}

enum relationship_type {
  mother
  father
  guardian
}

enum rubric_level {
  exemplary
  accomplished
  developing
  beginning
}

enum school_location_type {
  classroom
  laboratory
  gymnasium
  pool
  library
  auditorium
}

enum subject_thread_response_type {
  comment
  answer
}

enum subject_thread_type {
  discussion
  question
  announcement
  qanda
}

enum task_block_response_status {
  edit_permission
  submitted
  graded
}

enum task_block_type {
  h1
  h2
  h3
  h4
  h5
  h6
  markdown
  image
  video
  audio
  fill_in_blank
  multiple_choice
  whiteboard
  matching
  two_column_layout
  short_answer
}

enum task_status {
  draft
  in_progress
  published
  completed
  locked
  released
}

enum task_type {
  lesson
  assessment
  homework
}

enum tt_queue_status {
  queued
  in_progress
  completed
  failed
}

enum gender {
  male
  female
  "non-binary"
  other
  unspecified
}

enum user_honorific {
  Mr
  Ms
  Mrs
  Dr
  Prof
}

enum user_type {
  student
  teacher
  guardian
  principal
  schoolAdmin
  systemAdmin
}

enum whiteboard_object_type {
  Rect
  Circle
  Path
  Textbox
}

enum year_level {
  N
  F
  "1"
  "2"
  "3"
  "4"
  "5"
  "6"
  "7"
  "8"
  "9"
  "10"
  "10A"
  "11"
  "12"
  "13"
}

table answer {
  id integer [pk, not null]
  task_block_id integer [not null]
  answer jsonb
  marks "double precision"
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table ans_feed {
  id integer [pk, not null]
  ans_id integer [not null]
  task_block_response_id integer [not null]
  marks "double precision" [not null]
  feedbackLevel feedback_level
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table ass_pln_la_std {
  id integer [pk, not null]
  cm_itm_ass_pln_id integer [not null]
  la_std_id integer [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table ass_pln_res {
  id integer [pk, not null]
  cm_itm_ass_pln_id integer [not null]
  res_id integer [not null]
}

table campus {
  id integer [pk, not null]
  school_id integer [not null]
  name text [not null]
  address text [not null]
  description text
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table chatbot_chat {
  id integer [pk, not null]
  user_id uuid
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table chatbot_message {
  id integer [pk, not null]
  author_id uuid
  chat_id integer [not null]
  content text [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table task_response {
  id integer [pk, not null]
  class_task_id integer [not null]
  author_id uuid [not null]
  comment text
  feedback text
  marks "double precision" [not null]
  status task_block_response_status [not null, default: 'submitted']
  teacher_id uuid [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table task_response_resource {
  id integer [pk, not null]
  task_response_id integer [not null]
  resource_id integer [not null]
  author_id uuid [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table core_subject {
  id integer [pk, not null]
  name text [not null]
  description text
  cur_sub_id integer [not null]
  school_id integer [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table cm_itm {
  id integer [pk, not null]
  sub_off_id integer [not null]
  topic text [not null]
  description text
  start_week integer
  duration integer
  semester integer
  color text [default: '#3B82F6']
  image_base64 text
  original_id integer
  version integer [not null, default: 1]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    
    (original_id, version) [name: 'cm_itm_original_id_version_unique', unique]
  }
}

table cm_itm_ass_pln {
  id integer [pk, not null]
  cm_itm_id integer [not null]
  name text [not null]
  scope text[]
  description text
  rubric_id integer
  image_base64 text
  original_id integer
  version integer [not null, default: 1]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    
    (original_id, version) [name: 'cm_itm_ass_pln_original_id_version_unique', unique]
  }
}

table cm_itm_la {
  id integer [pk, not null]
  cm_itm_id integer [not null]
  lrn_a_id integer [not null]
  original_id integer
  version integer [not null, default: 1]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    
    (original_id, version) [name: 'cm_itm_la_original_id_version_unique', unique]
  }
}

table cm_itm_les_pln {
  id integer [pk, not null]
  cm_itm_id integer [not null]
  name text [not null]
  scope text[]
  description text
  image_base64 text
  original_id integer
  version integer [not null, default: 1]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    
    (original_id, version) [name: 'cm_itm_les_pln_original_id_version_unique', unique]
  }
}

table cm_itm_res {
  id integer [pk, not null]
  cm_itm_id integer [not null]
  resource_id integer [not null]
  original_id integer
  version integer [not null, default: 1]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    
    (original_id, version) [name: 'cm_itm_res_original_id_version_unique', unique]
  }
}

table criteria {
  id integer [pk, not null]
  task_block_id integer [not null]
  description text [not null]
  marks "double precision" [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table crit_fdbck {
  id integer [pk, not null]
  crit_id integer [not null]
  task_block_response_id integer [not null]
  feedbackLevel feedback_level
  marks "double precision" [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table curriculum {
  id integer [pk, not null]
  name text [not null]
  version text [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table curriculum_subject {
  id integer [pk, not null]
  name text [not null]
  cur_id integer [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table elective_subject {
  id integer [pk, not null]
  name text [not null]
  description text
  school_id integer [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table fet_activity {
  id integer [pk, not null]
  tt_id integer [not null]
  teacher_id text [not null]
  subject_id integer [not null]
  tt_group_id integer [not null]
  space_id integer [not null]
  tt_day_id integer [not null]
  tt_period_id integer [not null]
  duration integer [not null]
}

table learning_area {
  id integer [pk, not null]
  cur_sub_id integer [not null]
  name text [not null]
  description text
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table lrn_a_std {
  id integer [pk, not null]
  lrn_a_id integer [not null]
  name text [not null]
  description text
  yearLevel year_level [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table les_pln_la_std {
  id integer [pk, not null]
  cm_itm_les_pln_id integer [not null]
  la_std_id integer [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table les_pln_res {
  id integer [pk, not null]
  cm_itm_les_pln_id integer [not null]
  res_id integer [not null]
}

table resource {
  id integer [pk, not null]
  file_name text [not null]
  object_key text [not null]
  bucket_name text [not null, default: 'schools']
  content_type text [not null]
  file_size integer [not null]
  resource_type text [not null]
  uploaded_by text [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table rubric {
  id integer [pk, not null]
  title text [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table rubric_cell {
  id integer [pk, not null]
  row_id integer [not null]
  level rubric_level [not null]
  description text [not null]
  marks "double precision" [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table rubric_feedback {
  id integer [pk, not null]
  class_task_response_id integer [not null]
  rubric_row_id integer [not null]
  rubric_cell_id integer [not null]
  feedback text
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table rubric_row {
  id integer [pk, not null]
  rubric_id integer [not null]
  title text [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table school {
  id integer [pk, not null]
  name text [not null, unique]
  logo_url text
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table school_building {
  id integer [pk, not null]
  campus_id integer [not null]
  name text [not null]
  description text
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    (campus_id, name) [name: 'school_building_campus_id_name_unique', unique]
  }
}

table school_space {
  id integer [pk, not null]
  building_id integer [not null]
  name text [not null]
  type school_location_type [not null]
  capacity integer
  description text
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    (building_id, name) [name: 'school_space_building_id_name_unique', unique]
  }
}

table session {
  id text [pk, not null]
  user_id uuid [not null]
  expires_at "timestamp with time zone" [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table std_elab {
  id integer [pk, not null]
  lrn_a_std_id integer [not null]
  name text [not null]
  cont_elab text [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table subject {
  id integer [pk, not null]
  name text [not null]
  school_id integer [not null]
  core_sub_id integer
  elective_sub_id integer
  yearLevel year_level [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    (school_id, name) [name: 'subject_school_id_name_unique', unique]
    
  }
}

table sub_cls_allo {
  id integer [pk, not null]
  sub_off_cls_id integer [not null]
  sch_spa_id integer [not null]
  start_timestamp timestamp [not null]
  end_timestamp timestamp [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table sub_class_allo_attendance {
  id integer [pk, not null]
  sub_class_allo_id integer [not null]
  user_id uuid [not null]
  was_absent boolean [not null, default: false]
  did_attend boolean [not null, default: false]
  attendance_note text
  behaviour_note text
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    (sub_class_allo_id, user_id) [name: 'sub_class_allo_attendance_sub_class_allo_id_user_id_unique', unique]
  }
}

table sub_off {
  id integer [pk, not null]
  sub_id integer [not null]
  year integer [not null]
  semester integer [not null]
  campus_id integer [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table sub_off_cls {
  id integer [pk, not null]
  name text [not null]
  sub_off_id integer [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    (sub_off_id, name) [name: 'sub_off_cls_sub_off_id_name_unique', unique]
  }
}

table sub_off_class_resource {
  id integer [pk, not null]
  title text
  description text
  sub_off_class_id integer [not null]
  resource_id integer [not null]
  cm_item_id integer
  author_id uuid [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table sub_off_class_task {
  id integer [pk, not null]
  index integer [not null]
  status task_status [not null, default: 'draft']
  sub_off_class_id integer [not null]
  task_id integer [not null]
  author_id uuid [not null]
  cm_item_id integer
  week integer
  dueDate timestamp
  is_archived boolean [not null, default: false]
  rubric_id integer
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table sub_thread {
  id integer [pk, not null]
  type subject_thread_type [not null]
  sub_off_id integer [not null]
  user_id uuid [not null]
  title text [not null]
  content text [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table sub_thread_response {
  id integer [pk, not null]
  type subject_thread_response_type [not null]
  sub_thread_id integer [not null]
  user_id uuid [not null]
  content text [not null]
  parent_id integer
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table task {
  id integer [pk, not null]
  title text [not null]
  type task_type [not null]
  description text [not null]
  rubric_id integer
  original_id integer
  version integer [not null, default: 1]
  subject_offering_id integer [not null]
  ai_tutor_enabled boolean [not null, default: true]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    
    (original_id, version) [name: 'task_original_id_version_unique', unique]
  }
}

table task_block {
  id integer [pk, not null]
  task_id integer [not null]
  type task_block_type [not null]
  content jsonb [not null]
  index integer [not null, default: 0]
  available_marks integer
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table task_block_response {
  id integer [pk, not null]
  task_block_id integer [not null]
  author_id uuid [not null]
  class_task_id integer [not null]
  response jsonb
  feedback text
  marks "double precision"
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table task_standard {
  id integer [pk, not null]
  class_task_id integer [not null]
  la_standard_id integer [not null]
}

table tt {
  id integer [pk, not null]
  sch_id integer [not null]
  sch_year integer [not null]
  name text [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    (sch_id, name) [name: 'tt_sch_id_name_unique', unique]
  }
}

table tt_activity {
  id integer [pk, not null]
  tt_id integer [not null]
  subject_id integer [not null]
  teacher_id uuid [not null]
  tt_group_id integer [not null]
  periods_per_instance integer [not null, default: 1]
  total_periods integer [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table tt_day {
  id integer [pk, not null]
  tt_id integer [not null]
  day integer [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table tt_group {
  id integer [pk, not null]
  tt_id integer [not null]
  yearLevel year_level [not null]
  name text [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table tt_group_member {
  id integer [pk, not null]
  tt_group_id integer [not null]
  user_id uuid [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    (tt_group_id, user_id) [name: 'tt_group_member_tt_group_id_user_id_unique', unique]
  }
}

table tt_period {
  id integer [pk, not null]
  tt_id integer [not null]
  start_time time [not null]
  end_time time [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table tt_queue {
  id integer [pk, not null]
  tt_id integer [not null]
  user_id uuid [not null]
  file_name text [not null]
  status tt_queue_status [not null, default: 'queued']
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table user {
  id uuid [pk, not null, default: `gen_random_uuid()`]
  email text [not null, unique]
  password_hash text [not null]
  school_id integer [not null]
  type user_type [not null]
  gender gender
  date_of_birth "timestamp with time zone"
  honorific user_honorific
  yearLevel year_level [not null]
  first_name text [not null]
  middle_name text
  last_name text [not null]
  avatar_url text
  verification_code text
  email_verified boolean [not null, default: false]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table user_campus {
  id integer [pk, not null]
  user_id uuid [not null]
  campus_id integer [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table user_relationship {
  id uuid [pk, not null, default: `gen_random_uuid()`]
  user_id uuid [not null]
  related_user_id uuid [not null]
  relationshipType relationship_type [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table user_sub_off {
  id integer [pk, not null]
  user_id uuid [not null]
  sub_off_id integer [not null]
  is_complete integer [not null, default: 0]
  is_archived integer [not null, default: 0]
  color integer [not null, default: 100]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table user_sub_off_class {
  id integer [pk, not null]
  user_id uuid [not null]
  sub_off_class_id integer [not null]
  is_archived boolean [not null, default: false]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]

  indexes {
    (user_id, sub_off_class_id) [name: 'user_sub_off_class_user_id_sub_off_class_id_unique', unique]
  }
}

table whiteboard {
  id integer [pk, not null]
  task_id integer [not null]
  title text
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}

table whiteboard_object {
  id integer [pk, not null]
  whiteboard_id integer [not null]
  object_id text [not null, unique]
  objectType whiteboard_object_type [not null]
  object_data jsonb [not null]
  createdAt timestamp [not null, default: `now()`]
  updatedAt timestamp [not null, default: `now()`]
}