/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as InstitutionsIndexImport } from './routes/institutions/index'
import { Route as InstitutionsInstitutionIdIndexImport } from './routes/institutions/$institutionId/index'
import { Route as InstitutionsInstitutionIdCoursesIndexImport } from './routes/institutions/$institutionId/courses/index'
import { Route as InstitutionsInstitutionIdCoursesCourseIdWorkspacesImport } from './routes/institutions/$institutionId/courses/$courseId.workspaces'
import { Route as InstitutionsInstitutionIdCoursesCourseIdLessonsImport } from './routes/institutions/$institutionId/courses/$courseId.lessons'
import { Route as InstitutionsInstitutionIdCoursesCourseIdDiscussionImport } from './routes/institutions/$institutionId/courses/$courseId.discussion'
import { Route as InstitutionsInstitutionIdCoursesCourseIdChatImport } from './routes/institutions/$institutionId/courses/$courseId.chat'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const InstitutionsIndexRoute = InstitutionsIndexImport.update({
  path: '/institutions/',
  getParentRoute: () => rootRoute,
} as any)

const InstitutionsInstitutionIdIndexRoute =
  InstitutionsInstitutionIdIndexImport.update({
    path: '/institutions/$institutionId/',
    getParentRoute: () => rootRoute,
  } as any)

const InstitutionsInstitutionIdCoursesIndexRoute =
  InstitutionsInstitutionIdCoursesIndexImport.update({
    path: '/institutions/$institutionId/courses/',
    getParentRoute: () => rootRoute,
  } as any)

const InstitutionsInstitutionIdCoursesCourseIdWorkspacesRoute =
  InstitutionsInstitutionIdCoursesCourseIdWorkspacesImport.update({
    path: '/institutions/$institutionId/courses/$courseId/workspaces',
    getParentRoute: () => rootRoute,
  } as any)

const InstitutionsInstitutionIdCoursesCourseIdLessonsRoute =
  InstitutionsInstitutionIdCoursesCourseIdLessonsImport.update({
    path: '/institutions/$institutionId/courses/$courseId/lessons',
    getParentRoute: () => rootRoute,
  } as any)

const InstitutionsInstitutionIdCoursesCourseIdDiscussionRoute =
  InstitutionsInstitutionIdCoursesCourseIdDiscussionImport.update({
    path: '/institutions/$institutionId/courses/$courseId/discussion',
    getParentRoute: () => rootRoute,
  } as any)

const InstitutionsInstitutionIdCoursesCourseIdChatRoute =
  InstitutionsInstitutionIdCoursesCourseIdChatImport.update({
    path: '/institutions/$institutionId/courses/$courseId/chat',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/institutions/': {
      id: '/institutions/'
      path: '/institutions'
      fullPath: '/institutions'
      preLoaderRoute: typeof InstitutionsIndexImport
      parentRoute: typeof rootRoute
    }
    '/institutions/$institutionId/': {
      id: '/institutions/$institutionId/'
      path: '/institutions/$institutionId'
      fullPath: '/institutions/$institutionId'
      preLoaderRoute: typeof InstitutionsInstitutionIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/institutions/$institutionId/courses/': {
      id: '/institutions/$institutionId/courses/'
      path: '/institutions/$institutionId/courses'
      fullPath: '/institutions/$institutionId/courses'
      preLoaderRoute: typeof InstitutionsInstitutionIdCoursesIndexImport
      parentRoute: typeof rootRoute
    }
    '/institutions/$institutionId/courses/$courseId/chat': {
      id: '/institutions/$institutionId/courses/$courseId/chat'
      path: '/institutions/$institutionId/courses/$courseId/chat'
      fullPath: '/institutions/$institutionId/courses/$courseId/chat'
      preLoaderRoute: typeof InstitutionsInstitutionIdCoursesCourseIdChatImport
      parentRoute: typeof rootRoute
    }
    '/institutions/$institutionId/courses/$courseId/discussion': {
      id: '/institutions/$institutionId/courses/$courseId/discussion'
      path: '/institutions/$institutionId/courses/$courseId/discussion'
      fullPath: '/institutions/$institutionId/courses/$courseId/discussion'
      preLoaderRoute: typeof InstitutionsInstitutionIdCoursesCourseIdDiscussionImport
      parentRoute: typeof rootRoute
    }
    '/institutions/$institutionId/courses/$courseId/lessons': {
      id: '/institutions/$institutionId/courses/$courseId/lessons'
      path: '/institutions/$institutionId/courses/$courseId/lessons'
      fullPath: '/institutions/$institutionId/courses/$courseId/lessons'
      preLoaderRoute: typeof InstitutionsInstitutionIdCoursesCourseIdLessonsImport
      parentRoute: typeof rootRoute
    }
    '/institutions/$institutionId/courses/$courseId/workspaces': {
      id: '/institutions/$institutionId/courses/$courseId/workspaces'
      path: '/institutions/$institutionId/courses/$courseId/workspaces'
      fullPath: '/institutions/$institutionId/courses/$courseId/workspaces'
      preLoaderRoute: typeof InstitutionsInstitutionIdCoursesCourseIdWorkspacesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/institutions': typeof InstitutionsIndexRoute
  '/institutions/$institutionId': typeof InstitutionsInstitutionIdIndexRoute
  '/institutions/$institutionId/courses': typeof InstitutionsInstitutionIdCoursesIndexRoute
  '/institutions/$institutionId/courses/$courseId/chat': typeof InstitutionsInstitutionIdCoursesCourseIdChatRoute
  '/institutions/$institutionId/courses/$courseId/discussion': typeof InstitutionsInstitutionIdCoursesCourseIdDiscussionRoute
  '/institutions/$institutionId/courses/$courseId/lessons': typeof InstitutionsInstitutionIdCoursesCourseIdLessonsRoute
  '/institutions/$institutionId/courses/$courseId/workspaces': typeof InstitutionsInstitutionIdCoursesCourseIdWorkspacesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/institutions': typeof InstitutionsIndexRoute
  '/institutions/$institutionId': typeof InstitutionsInstitutionIdIndexRoute
  '/institutions/$institutionId/courses': typeof InstitutionsInstitutionIdCoursesIndexRoute
  '/institutions/$institutionId/courses/$courseId/chat': typeof InstitutionsInstitutionIdCoursesCourseIdChatRoute
  '/institutions/$institutionId/courses/$courseId/discussion': typeof InstitutionsInstitutionIdCoursesCourseIdDiscussionRoute
  '/institutions/$institutionId/courses/$courseId/lessons': typeof InstitutionsInstitutionIdCoursesCourseIdLessonsRoute
  '/institutions/$institutionId/courses/$courseId/workspaces': typeof InstitutionsInstitutionIdCoursesCourseIdWorkspacesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/institutions/': typeof InstitutionsIndexRoute
  '/institutions/$institutionId/': typeof InstitutionsInstitutionIdIndexRoute
  '/institutions/$institutionId/courses/': typeof InstitutionsInstitutionIdCoursesIndexRoute
  '/institutions/$institutionId/courses/$courseId/chat': typeof InstitutionsInstitutionIdCoursesCourseIdChatRoute
  '/institutions/$institutionId/courses/$courseId/discussion': typeof InstitutionsInstitutionIdCoursesCourseIdDiscussionRoute
  '/institutions/$institutionId/courses/$courseId/lessons': typeof InstitutionsInstitutionIdCoursesCourseIdLessonsRoute
  '/institutions/$institutionId/courses/$courseId/workspaces': typeof InstitutionsInstitutionIdCoursesCourseIdWorkspacesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/institutions'
    | '/institutions/$institutionId'
    | '/institutions/$institutionId/courses'
    | '/institutions/$institutionId/courses/$courseId/chat'
    | '/institutions/$institutionId/courses/$courseId/discussion'
    | '/institutions/$institutionId/courses/$courseId/lessons'
    | '/institutions/$institutionId/courses/$courseId/workspaces'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/institutions'
    | '/institutions/$institutionId'
    | '/institutions/$institutionId/courses'
    | '/institutions/$institutionId/courses/$courseId/chat'
    | '/institutions/$institutionId/courses/$courseId/discussion'
    | '/institutions/$institutionId/courses/$courseId/lessons'
    | '/institutions/$institutionId/courses/$courseId/workspaces'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/institutions/'
    | '/institutions/$institutionId/'
    | '/institutions/$institutionId/courses/'
    | '/institutions/$institutionId/courses/$courseId/chat'
    | '/institutions/$institutionId/courses/$courseId/discussion'
    | '/institutions/$institutionId/courses/$courseId/lessons'
    | '/institutions/$institutionId/courses/$courseId/workspaces'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  InstitutionsIndexRoute: typeof InstitutionsIndexRoute
  InstitutionsInstitutionIdIndexRoute: typeof InstitutionsInstitutionIdIndexRoute
  InstitutionsInstitutionIdCoursesIndexRoute: typeof InstitutionsInstitutionIdCoursesIndexRoute
  InstitutionsInstitutionIdCoursesCourseIdChatRoute: typeof InstitutionsInstitutionIdCoursesCourseIdChatRoute
  InstitutionsInstitutionIdCoursesCourseIdDiscussionRoute: typeof InstitutionsInstitutionIdCoursesCourseIdDiscussionRoute
  InstitutionsInstitutionIdCoursesCourseIdLessonsRoute: typeof InstitutionsInstitutionIdCoursesCourseIdLessonsRoute
  InstitutionsInstitutionIdCoursesCourseIdWorkspacesRoute: typeof InstitutionsInstitutionIdCoursesCourseIdWorkspacesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  InstitutionsIndexRoute: InstitutionsIndexRoute,
  InstitutionsInstitutionIdIndexRoute: InstitutionsInstitutionIdIndexRoute,
  InstitutionsInstitutionIdCoursesIndexRoute:
    InstitutionsInstitutionIdCoursesIndexRoute,
  InstitutionsInstitutionIdCoursesCourseIdChatRoute:
    InstitutionsInstitutionIdCoursesCourseIdChatRoute,
  InstitutionsInstitutionIdCoursesCourseIdDiscussionRoute:
    InstitutionsInstitutionIdCoursesCourseIdDiscussionRoute,
  InstitutionsInstitutionIdCoursesCourseIdLessonsRoute:
    InstitutionsInstitutionIdCoursesCourseIdLessonsRoute,
  InstitutionsInstitutionIdCoursesCourseIdWorkspacesRoute:
    InstitutionsInstitutionIdCoursesCourseIdWorkspacesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/login",
        "/signup",
        "/institutions/",
        "/institutions/$institutionId/",
        "/institutions/$institutionId/courses/",
        "/institutions/$institutionId/courses/$courseId/chat",
        "/institutions/$institutionId/courses/$courseId/discussion",
        "/institutions/$institutionId/courses/$courseId/lessons",
        "/institutions/$institutionId/courses/$courseId/workspaces"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/institutions/": {
      "filePath": "institutions/index.tsx"
    },
    "/institutions/$institutionId/": {
      "filePath": "institutions/$institutionId/index.tsx"
    },
    "/institutions/$institutionId/courses/": {
      "filePath": "institutions/$institutionId/courses/index.tsx"
    },
    "/institutions/$institutionId/courses/$courseId/chat": {
      "filePath": "institutions/$institutionId/courses/$courseId.chat.tsx"
    },
    "/institutions/$institutionId/courses/$courseId/discussion": {
      "filePath": "institutions/$institutionId/courses/$courseId.discussion.tsx"
    },
    "/institutions/$institutionId/courses/$courseId/lessons": {
      "filePath": "institutions/$institutionId/courses/$courseId.lessons.tsx"
    },
    "/institutions/$institutionId/courses/$courseId/workspaces": {
      "filePath": "institutions/$institutionId/courses/$courseId.workspaces.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
