//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Course struct {
	ID            int32 `sql:"primary_key"`
	InstitutionId int32
	Name          string
	Description   string
	CreatedAt     *time.Time
	ModifiedAt    *time.Time
}
